// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dfp
Rcpp::List dfp(const Rcpp::List vars, Rcpp::Function fn);
RcppExport SEXP _BhatF_dfp(SEXP varsSEXP, SEXP fnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type vars(varsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type fn(fnSEXP);
    rcpp_result_gen = Rcpp::wrap(dfp(vars, fn));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BhatF_dfp", (DL_FUNC) &_BhatF_dfp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_BhatF(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
