# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' dfp
#'
#' Call Davidon-Fletcher-Powell optimization Fortran routine
#'
#' @param vars List with components:
#' 'label' (character vector),
#' 'est' (initial guess vector),
#' 'low' (lower bounds vector),
#' 'upp' (upper bounds vector)
#' 'fixed' (optional, logicals vector, TRUE if variable to be held constant)
#' @param fn R Function to be optimized
#' @export
dfp <- function(vars, fn) {
    .Call(`_BhatF_dfp`, vars, fn)
}

