# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' call_migrad
#'
#' Call migrad subroutine
#'
#' @param vars List with components:
#' 'label' (character vector),
#' 'est' (initial guess vector),
#' 'low' (lower bounds vector),
#' 'upp' (upper bounds vector)
#' 'fixed' (optional, logicals vector, TRUE if variable to be held constant)
#' @param fn R Function to be optimized
#' @export
call_migrad <- function(vars, fn) {
    .Call(`_BhatF_call_migrad`, vars, fn)
}

