# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' call_migrad
#'
#' Call migrad subroutine
#'
#' @param vars Matrix of variables, 1 row/variable containing is_fixed,initial,estimated,min,max
#' @export
call_migrad <- function(vars, fn) {
    .Call(`_BhatF_call_migrad`, vars, fn)
}

